name: DeepTE
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.15
  - tensorflow-gpu=1.14.0
  - biopython
  - keras=2.2.4
  - numpy=1.23.4
  - scikit-learn
  - matplotlib
  - seaborn
  - rmblast
  - pip
  - pip:
    - openpyxl
